HISTSIZE=100000
HISTFILESIZE=2000

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$⚡️  '
else
    #PS1='${debian_chroot:+($debian_chroot)}\u@\h.io:\w\$ '
    #PS1='${debian_chroot:+($debian_chroot)}\h.io:\w\$ '
    #PS1='\h:\W \u\$ 🍔   '
    #PS1='\h:\W \u\$ 🍺  🍔  '
    #PS1='\h:\W \u\$ 🍺  '
    #PS1='\h:\W \u\$ 🏃  '
    #PS1='\h:\W \u\$ ☀ ☁  ⛪  🏪    🏣_  🏢  🏠  🏥  🏬    '
    #PS1='\h:\W \u\$  🏠  🏪   🚘   🏢  🏡        🏢  🌳  '
    #PS1='\h:\W \u\$ 🚶  🏃  🚶  🏃  '
    #PS1='\h:\W \u\$ ⚡️  '
    PS1="\[\e[00;31m\]:\[\e[0m\]\[\e[00;32m\]\h\[\e[0m\]\[\e[00;31m\]:\[\e[0m\]\[\e[00;33m\]\W\[\e[0m\]\[\e[00;31m\]:\[\e[0m\]\[\e[00;37m\]\\$\[\e[0m\]⚡️  "
fi

alias solo-dch='sudo chef-solo -c /home/dchoi/chef-repo/solo.rb -j /home/dchoi/chef-repo/localhost.json'
alias solo-nginx='sudo chef-solo -c /home/dchoi/chef-repo/solo.rb -j /home/dchoi/chef-repo/localhost-nginx.json'
