
"---------- Base Configs ------------------------------------------------------------

syntax on
set nocompatible          " no need to be compatible with old vim
set shiftwidth=2          " Set the default shift width for indents
set hlsearch              " highlight search
set ignorecase            " Do case in sensitive matching with
set smartcase             " be sensitive when there's a capital letter
set incsearch
set showmatch             " Show matching brackets.
set cursorline
set history=256000        " Number of things to remember in history.
set vb										" Enable visual bell disable any beeps or flashes on error
set laststatus=2          " Always show status line.
set clipboard+=unnamed    " Yanks go on clipboard instead.

"set ruler                 " Show ruler
"set bs=2
"set list
"set autowrite             " Writes on make/shell commands
"set autoread
"set timeoutlen=250        " Time to wait after ESC (default causes an annoying delay)
"set number                " Show line numbers
"set directory=/tmp//      " prepend(^=) $HOME/.tmp/ to default path; use full path as backup filename(//)
"set hidden                " The current buffer can be put to the background without writing to disk

set nowritebackup
set nobackup
set fo-=t										" Do no auto-wrap text using textwidth (does not apply to comments)
set wrap
set textwidth=0                  " Don't wrap lines by default
set backspace=indent,eol,start " more powerful backspacing
"set smartindent
set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
set tabstop=2								" Set the default tabstop
set softtabstop=2
set expandtab             " Make tabs into spaces (set by tabstop)

set matchtime=5							" Bracket blinking.
set novisualbell						" No blinking
set noerrorbells						" No noise.
"set showcmd								" Display an incomplete command in the lower right corner of the Vim window
set equalalways
set splitbelow
set splitright

"---------- Color and Visual ------------------------------------------------------------

set statusline=%F%m%r%h%w\ %{fugitive#statusline()}\ [%l,%c]\ [%L,%p%%]		" put useful info in status bar
set background=dark					"set background and color scheme
colorscheme desert					"iTerm color scheme

highlight clear SignColumn
highlight VertSplit    ctermbg=236
highlight ColorColumn  ctermbg=237
highlight LineNr       ctermbg=236 ctermfg=240
highlight CursorLineNr ctermbg=236 ctermfg=240
highlight CursorLine   ctermbg=236
highlight StatusLineNC ctermbg=238 ctermfg=0
highlight StatusLine   ctermbg=240 ctermfg=12
"highlight IncSearch    ctermbg=0   ctermfg=3
"highlight Search       ctermbg=0   ctermfg=9
highlight Visual       ctermbg=3   ctermfg=0
highlight Pmenu        ctermbg=240 ctermfg=12
highlight PmenuSel     ctermbg=0   ctermfg=3
highlight SpellBad     ctermbg=0   ctermfg=1


if version >= 700
  au InsertEnter * hi StatusLine ctermfg=235 ctermbg=2
  au InsertLeave * hi StatusLine ctermbg=240 ctermfg=12
endif

"==== Highlight extra white spaces
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()


"---------- Vundle Configs ------------------------------------------------------------
filetype off                " required!

"==== Setup Vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

"==== Plugins
Bundle "tpope/vim-rails"
Bundle "tpope/vim-fugitive"
Bundle "tpope/vim-commentary"
Bundle "tpope/vim-endwise"
Bundle "tpope/vim-markdown"
Bundle "tpope/vim-rake"
Bundle "tpope/vim-haml"
Bundle "tpope/vim-repeat"
Bundle "tpope/vim-bundler"
Bundle 'mattn/zencoding-vim'
Bundle 'msanders/snipmate.vim'
"Bundle "ervandew/supertab"			# tab completion
Bundle "mileszs/ack.vim"

"==== Navigation
Bundle "kien/ctrlp.vim"
Bundle "scrooloose/nerdtree"

"==== Programming
Bundle "groenewege/vim-less"
Bundle "kchmck/vim-coffee-script"
Bundle "nono/vim-handlebars"
Bundle "slim-template/vim-slim"
Bundle "vim-ruby/vim-ruby"
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins

Bundle "leshill/vim-json"
Bundle "pangloss/vim-javascript"
Bundle "vim-scripts/matchit.zip"
Bundle "othree/html5.vim"
Bundle "alfredodeza/jacinto.vim"
Bundle "jistr/vim-nerdtree-tabs"

"==== Utility
Bundle "Rykka/colorv.vim"
Bundle "godlygeek/tabular"
Bundle "vim-scripts/AutoTag"

"==== Vroom
Bundle "skalnik/vim-vroom"
let g:vroom_map_keys = 0
map <leader>t :VroomRunTestFile<cr>
map <leader>T :VroomRunNearestTest<cr>

"==== Colorscheme
"Bundle \"altercation/vim-colors-solarized"
"let g:solarized_termcolors=256
"set background=light
"set background=dark
"colorscheme solarized


"---------- General Configs ------------------------------------------------------------
"autocmd VimEnter * NERDTree
"autocmd BufEnter * NERDTreeMirror
"autocmd VimEnter * wincmd w


"==== Auto commands
au BufRead,BufNewFile {Gemfile,config.ru,*.thor}  set ft=ruby
au BufRead,BufNewFile {*.md,*.mkd,*.markdown}     set ft=markdown
au BufRead,BufNewFile {COMMIT_EDITMSG}            set ft=gitcommit

"==== Key mappings
" Clear last search highlighting
nnoremap <Space> :noh<cr>
let mapleader = ","         " Change leader key

"==== Navigating between windows
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

"==== Keep content after pasting
vnoremap <leader>p "_dP

"==== Run cucumber
"silent! map <unique> <Leader>w :!bundle exec cucumber --profile=wip<CR>

"==== Fix for rvm
set shell=/bin/sh
set pastetoggle=<F2>

"==== sudo write
"cmap w!! %!sudo tee > /dev/null %

"==== Custom functions
function! VisualSelection()
  try
    let a_save = @a
    normal! gv"ay
    return @a
  finally
    let @a = a_save
  endtry
endfunction

function! SearchProjectForSelect()
  exec ":Ack \"" . VisualSelection() . "\""
endfunction

map <leader>s :call SearchProjectForSelect()<cr>


"EOF
